# Generated by Django 5.1.2 on 2024-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
